### ISSUE TITLE
"c" example doesn't work

### ISSUE THREAD

**Issue by radix** [mingqi/clj-struct#1]
characters aren't working as shown in the example in the README.

user=> (pack "c" \a)
ClassCastException java.lang.Character cannot be cast to java.lang.Number  clojure.lang.RT.longCast (RT.java:1127)

**Comment by mingqi** [comment]
it's works my here. what's your clojure version? below is my lein project.clj:

## project.clj

(defproject test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [clj-struct "0.1.0"]]
  :profiles
  {:dev {:dependencies [[ring-mock "0.1.3"]]}}
            )

---

user=> (use 'clj-struct.core)
nil
user=>  (pack "c" \a)
[97]

**Comment by mingqi** [comment]
please feel free reopen this if you still have issue.

**Comment by radix** [comment]
You're right, sorry, I was using an old version of Clojure.
